<!doctype html>
<html>


    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title><?php echo $this->page_name; ?></title>
        <meta name="author" content="Jake Rocheleau">
        <link rel="shortcut icon" href="http://www.templatemonster.com/favicon.ico">
        <link rel="icon" href="http://www.templatemonster.com/favicon.ico">
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo root_url; ?>/data/css/video_styles.css">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/bootstrap.css">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/bootstrap-theme.min.css">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/bootstrap-theme.css">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/bootstrap-theme.css.map">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/bootstrap.css.map">
        <link rel="stylesheet" type="text/css"  href="<?php echo root_url; ?>/data/css/tab.css.map">


        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/jquery-ui-1.8.22.custom.min.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/jquery.imagesloaded.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/video.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/bigvideo.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/bootstrap.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo root_url; ?>/data/js/npm.js"></script>

    </head>
    <body>

        <div class="container" style="margin-top: 50px">
            <div id="blockcontent" class=" container">
                <div class="col-md-12">
                    <h1 style="text-align: center">Welcome to Exam Monkey</h1>
                    <br/><br/>
                    <div class="tabbable-panel">
                        <div class="tabbable-line">
                            <ul class="nav nav-tabs ">
                                <li class="<?php
                                if (!isset($this->login_error)) {
                                    echo "active";
                                }
                                ?>">
                                    <a href="#tab_default_1" data-toggle="tab">
                                        <h4>Take An Exam</h4></a>
                                </li>
                                <li class="<?php
                                if (isset($this->login_error)) {
                                    echo "active";
                                }
                                ?>">
                                    <a href="#tab_default_2" data-toggle="tab">
                                        <h4>Set up an Exam</h4> </a>
                                </li>

                            </ul>
                            <br/><br/>
                            <div class="tab-content">
                                <div class="tab-pane <?php
                                if (!isset($this->login_error)) {
                                    echo "active";
                                }
                                ?>" id="tab_default_1">

                                    <div class="form-group">
                                        <h1 class="text-center text-success">Enter your exam code:</h1>
                                        <form  class="form-horizontal" role="form"
                                               action="<?php echo root_url; ?>/exam/start-exam" method="POST">
                                            <div class="">
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="examCode" name="code" 
                                                           placeholder="Exam code"></div>
                                                <div class="col-sm-2">
                                                    <button type="submit" class="btn btn-success">Start Exam</button>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                                <div class="tab-pane <?php
                                if (isset($this->login_error)) {
                                    echo "active";
                                }
                                ?>" id="tab_default_2">
                                    <form class="form-horizontal" role="form"
                                          action="" method="POST">
                                        <div class="form-group" >
                                            <div class="col-sm-2">
                                                <label for="username" class="control-label">Email</label>
                                            </div>
                                            <div class="col-sm-10">
                                                <input type="text" name="username" class="form-control" id="username" placeholder="Username">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-2">
                                                <label for="password" class="control-label">Password</label></div>
                                            <div class="col-sm-10">
                                                <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <label style="color:red"><?php
                                                    if (isset($this->login_error)) {
                                                        echo $this->login_error;
                                                    }
                                                    ?></label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="col-md-3 btn-success btn btn-default">Sign in</button>
                                                <a href="<?php echo root_url . '/user/register' ?>">
                                                    <buttton  class="col-md-3 col-md-offset-1 btn btn-default btn-primary">
                                                        Register
                                                    </button></a>

                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                /**
                 * video source: http://beachfrontprod.blogspot.com/2011/09/random-footage-clip-2.html
                 */
                $(function() {
                    var BV = new $.BigVideo({useFlashForFirefox: false});

                    BV.init();
                    BV.show('<?php echo root_url; ?>/data/media/rochester-falls.mp4',
                            {altSource: '<?php echo root_url; ?>/data/media/river.ogv', ambient: true});
                });
            </script>

    </body>
</html>