<div class="col-md-12">
    <table class="table">
        <thead>
            <tr><th>No<?php echo $this->test; ?></th>
                <th>Exam Name</th>
                <th>Status</th>//this can be a dropdown box
                <th>Make it</th>
            </tr>
        </thead>
        <tbody>
            <tr><td>1</td>
                <td>Mark</td>
                <td><select>
                        <option>Open</option>
                        <option>Close</option>    
                    </select></td>
                    <td><a><button class="btn btn-success">Show Details</button></a></td>
            </tr>
                <tr><td>1</td>
                <td>Mark</td>
                <td><select>
                        <option>Open</option>
                        <option>Close</option>
                    </select></td>
                    <td><a><button class="btn btn-success">Show Details</button></a></td>
            </tr>    
            <tr><td>1</td>
                <td>Mark</td>
                <td><select>
                        <option>Open</option>
                        <option>Close</option>
                    </select></td>
                    <td><a><button class="btn btn-success">Show Details</button></a></td>
            </tr>
        </tbody>
    </table>
</div>
