


<div class="row">
    <div class="col-md-6">
        <form role="form" method="POST" action="">
            <div class="form-group">
                <label class="control-label" for="exampleInputEmail1">Email Address</label>
                <input class="form-control" id="email" name="email"
                       placeholder="Enter email" type="email">
            </div>
            <div class="form-group">
                <label class="control-label" for="exampleInputPassword1">Password</label>
                <input class="form-control" id="password" name="password"
                       placeholder="Password" type="password">
            </div>
            <button type="submit" class="btn btn-default">Register</button>
        </form>
    </div>
</div>
