

<div class="row">
    <div class="col-md-6">
        <form role="form" method="POST" action="">
            <div class="form-group">
                <label class="control-label" for="">Exam Name</label>
                <input class="form-control" id="examName" name="examName"
                       placeholder="examName" type="email">
            </div>
            <div class="form-group">
                <label class="control-label" for="">Exam Duration(mins)<label>
                        <select name="examDuration">
                            <option value="15">15</option>
                            <option value="30">30</option>
                            <option value="45">45</option>
                            <option value="60">60</option>
                            <option value="75">75</option>
                            <option value="90">90</option>
                        </select>
                        </div>
                      <div class="form-group">
                <label class="control-label" for="">Exam Questions no(mins)<label>
                        <select name="examQNum">
                            <?php for($i=0;$i<30;$i++){ ?>
                            <option>echo $i;</option>
                            <?php }?>
                        </select>
                        </div>
                        <button type="submit" class="btn btn-default">Add Questions</button>
                        </form>
                        </div>
                        </div>
