
<div class="row">
    <div class="col-md-6">
        <form role="form" method="POST" action="<?php echo root_url . "/exam/add-exam"; ?>" id="form1">
            <div class="form-group">
                <label class="control-label" for="">Exam Name</label>
                <input class="form-control" id="examName" name="exam_name"
                       placeholder="examName" type="text">
            </div>
            <div class="form-group">
                <label class="control-label" for="">Exam Duration(mins)

                    <label>
                        <select  name="exam_duration" id="exam_duration">
                            <option value="15">15</option>
                            <option value="30">30</option>
                            <option value="45">45</option>
                            <option value="60">60</option>
                            <option value="75">75</option>
                            <option value="90">90</option>
                        </select>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="">Exam Questions no(mins)<label>
                                    <select name="exam_no" id="exam_no">
                                        <?php
                                        for ($i = 0; $i < 30; $i++) {
                                            echo "<option value=\"$i\">" . $i . "</option>";
                                        }
                                        ?>
                                    </select>
                                    </div>
                                    <input type="submit" value="submit">
                                    </form>
                                    </div>
                                    </div>
