<div class="tabbable-panel">
    <div class="tabbable-line">
        <ul class="nav nav-tabs ">
            <li class="active">
                <a href="#basic_info_tab" data-toggle="tab">
                    <h4>Exam Basic Info</h4></a>
            </li>
            <li>
                <a href="#questions_tab" data-toggle="tab">
                    <h4>Exam Questions:</h4> </a>
            </li>
            <li>
                <a href="#analyse_tab" data-toggle="tab">
                    <h4>Analyse Report</h4> </a>
            </li>

        </ul>
        <br/>
        <div class="tab-content">
            <div class="tab-pane active" id="basic_info_tab">


                <div class="jumbotron">  
                    <div class="container">
                        <div class="row">
                            <h3 class="text-danger">
                                <div class="btn-primary col-md-4">Exam Name:</div>
                                <div class="btn-success col-md-8">Exam 123</div>

                                <hr>  <hr>
                                <div class="btn-primary col-md-4">Exam Duration(mins):</div>
                                <div class="btn-success col-md-8">32</div>
                                <hr>  <hr>
                                <div class="btn-primary col-md-4">Exam Status</div>
                                <div class="btn-success col-md-8">Private</div>
                                <hr>  <hr>
                                <div class="btn-primary col-md-4">Exam Code</div>
                                <div class="btn-success col-md-8">Not Available</div>
                            </h3>
                        </div>

                    </div>
                </div>
            </div>


            <!--exam questions-->
            <div class="tab-pane " id="questions_tab">
                <div class="section">
                    <div class="container">
                        <!--                        <div class="row">
                                                    <div class="col-md-12">
                                                        <span><h2>Questions:&nbsp;&nbsp;<select>
                                                                    <option>1</option>
                                                                                                                <option>2</option>
                                                                    <option>3</option>
                        
                                                                </select><br/></h2></span>
                        
                                                       
                                                    </div>
                                                </div>-->
                        <br/>
                        <div class="tabbable-panel">
                            <div class="tabbable-line">

                                <div class="tab-content">
                                    <?php for ($i = 0; $i < 2; $i++) { ?>
                                        <div class="tab-pane <?php
                                        if ($i == 0) {

                                            echo "active";
                                        }
                                        ?>" id="page<?php echo $i + 1; ?>">

                                            <div class="row">
                                             
                                                <div class="col-md-12">
                                                    <ul class="list-group">
                                                        <li class="list-group-item list-group-item-success">
                                                            <h4><?php echo $i; ?>. whAT IS FOYDSOUF ADHSFA,SDJFHKASDHF ASKDJ
                                                            </h4></li>
                                                        <li class="list-group-item">
                                                            A. COMPUTER IS ONE OF THE BEST INVENTATION IN THIS WORLD</li>
                                                        <li class="list-group-item">
                                                            A. COMPUTER IS ONE OF THE BEST INVENTATION IN THIS WORLD</li>
                                                        <li class="list-group-item">
                                                            A. COMPUTER IS ONE OF THE BEST INVENTATION IN THIS WORLD</li>
                                                        <li class="list-group-item">
                                                            A. COMPUTER IS ONE OF THE BEST INVENTATION IN THIS WORLD</li>
                                                        <li class="list-group-item">
                                                            <i class="fa fa-3x fa-fw fa-edit"></i>
                                                            <i class="fa fa-3x fa-fw fa-remove"></i>
                                                        </li>
                                                    </ul>

                                                </div>
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>

                                <ul class="nav nav-tabs">
                                    <li><a href="#page1" data-toggle="tab">1</a></li>
                                    <li><a href="#page2" data-toggle="tab">2</a></li>
                                </ul>
                            </div></div>
                    </div>
                </div>

            </div>
            <div class="tab-pane" id="analyse_tab">

            </div>

        </div>
    </div>
</div>