<div class="tabbable-panel">
    <div class="tabbable-line">
        <ul class="nav nav-tabs ">
            <li class="active">
                <a href="#basic_info_tab" data-toggle="tab">
                    <h4>Exam Basic Info</h4></a>
            </li>
            <li>
                <a href="#questions_tab" data-toggle="tab">
                    <h4>Exam Questions:</h4> </a>
            </li>
            <li>
                <a href="#analyse_tab" data-toggle="tab">
                    <h4>Analyse Report</h4> </a>
            </li>

        </ul>
        <br/>
        <div class="tab-content">
            <div class="tab-pane active" id="basic_info_tab">


                <div class="jumbotron">  
                    <div class="container">
                        <div class="row">
                            <h3 class="text-danger">
                                <div class="btn-primary col-md-4">Exam Name:</div>
                                <div class="btn-success col-md-8"><?php echo $this->basic_info['exam_name'];?></div>

                                <hr>  <hr>
                                <div class="btn-primary col-md-4">Exam Duration(mins):</div>
                                <div class="btn-success col-md-8"><?php echo $this->basic_info['duration'];?></div>
                                <hr>  <hr>
                                <div class="btn-primary col-md-4">Exam Status</div>
                                <div class="btn-success col-md-8"><?php echo $this->basic_info['status'];?></div>
                                <hr>  <hr>
                                <div class="btn-primary col-md-4">Exam Code</div>
                                <div class="btn-success col-md-8"><?php echo $this->basic_info['code'];?></div>
                            </h3>
                        </div>

                    </div>
                </div>
            </div>


            <!--exam questions-->
            <div class="tab-pane " id="questions_tab">
                <div class="section">
                    <div class="container">
                        <br/>
                        <div class="tabbable-panel">
                            <div class="tabbable-line">
                                <ul class="nav nav-tabs">
                                 
                                    <?php for($i=1;$i<$this->basic_info['total_question']+1;$i++){
                                        echo "<li><a href=\"#page$i\" data-toggle=\"tab\">$i</a></li>";
                                    }?>
                                </ul>
                                <div class="tab-content">
                                    <?php for ($i = 0; $i < $this->basic_info['total_question']; $i++) { ?>
                                        <div class="tab-pane <?php
                                        if ($i == 0) {

                                            echo "active";
                                        }
                                        ?>" id="page<?php echo $i + 1; ?>">

                                            <div class="row">
                                             
                                                <div class="col-md-12">
                                                    <ul class="list-group">
                                                        <li class="list-group-item list-group-item-success">
                                                            <h4><?php echo ($i+1).".".$this->questions[$i]['title']; ?>
                                                            </h4></li>
                                                        <li class="list-group-item">
                                                            A. <?php echo $this->questions[$i]['A'];?></li>
                                                        <li class="list-group-item">
                                                            B. <?php echo $this->questions[$i]['B'];?></li>
                                                        <li class="list-group-item">
                                                            C. <?php echo $this->questions[$i]['C'];?></li>
                                                        <li class="list-group-item">
                                                            D. <?php echo $this->questions[$i]['D'];?></li>
                                                        <li class="list-group-item">
                                                            <i class="fa fa-3x fa-fw fa-edit"></i>
                                                            <i class="fa fa-3x fa-fw fa-remove"></i>
                                                        </li>
                                                    </ul>

                                                </div>
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>

                               
                            </div></div>
                    </div>
                </div>

            </div>
            <div class="tab-pane" id="analyse_tab">

            </div>

        </div>
    </div>
</div>