   
<div class="container">
    <form method="POST" action="">
        <input type="hidden" name="total_question" value="<?php echo $this->basic_info['total_question'] ?>">
        <input type="hidden" name="exam_name" value="<?php echo $this->basic_info['exam_name'] ?>">

        <div class="tabbable-panel">
            <div class="tabbable-line">
                <ul class="nav nav-tabs">

                    <?php
                    for ($i = 1; $i < $this->basic_info['total_question'] + 1; $i++) {
                        echo "<li><a href=\"#page$i\" data-toggle=\"tab\">$i</a></li>";
                    }
                    ?>
                    <li><a href="#rank" data-toggle="tab">Rank It</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane" id="rank">
                        <div class="col-md-12 row">
                            <ul class="list-group">
                                <li class="list-group-item">
                                    <label><input type="radio" name="rank" value="Hard"> 
                                        Difficult</label>
                                </li>
                                <li class="list-group-item">
                                    <label><input type="radio" name="rank" value="Medium"> 
                                        Medium</label>
                                </li>    
                                <li class="list-group-item">
                                    <label><input type="radio" name="rank" value="Easy"> 
                                        Easy</label>
                                </li>

                        </div>
                    </div>
                    <?php for ($i = 0; $i < $this->basic_info['total_question']; $i++) { ?>
                        <div class="tab-pane <?php
                        if ($i == 0) {

                            echo "active";
                        }
                        ?>" id="page<?php echo $i + 1; ?>">
                            <div class="col-md-12 row">
                                <ul class="list-group">
                                    <li class="list-group-item list-group-item-success">
                                        <h4><?php echo ($i + 1) . "." . $this->questions[$i]['title']; ?>
                                        </h4></li>
                                    <li class="list-group-item">
                                        <label><input type="radio" name="answer_<?php echo $i; ?>" value="<?php echo $this->questions[$i]['A']; ?>"> 
                                            A. <?php echo $this->questions[$i]['A']; ?></label> </li>
                                    <li class="list-group-item">
                                        <label><input type="radio" name="answer_<?php echo $i; ?>" value="<?php echo $this->questions[$i]['B']; ?>"> 
                                            B. <?php echo $this->questions[$i]['B']; ?></label> </li>
                                    <li class="list-group-item">
                                        <label><input type="radio" name="answer_<?php echo $i; ?>" value="<?php echo $this->questions[$i]['C']; ?>"> 
                                            C. <?php echo $this->questions[$i]['C']; ?></label> </li>
                                    <li class="list-group-item">
                                        <label><input type="radio" name="answer_<?php echo $i; ?>" value="<?php echo $this->questions[$i]['D']; ?>"> 
                                            D. <?php echo $this->questions[$i]['D']; ?></label> </li>

                                </ul>

                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <input class="btn btn-default btn-block" type="submit">
        </div>
    </form>
</div>
